<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="He Zou">
<meta name="dcterms.date" content="2026-05-15">

<title>Poisson Regression and Maximum Likelihood Estimation – Raven’s Website</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Raven’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a>
  <ul class="collapse">
  <li><a href="#patent-awards-by-customer-status" id="toc-patent-awards-by-customer-status" class="nav-link" data-scroll-target="#patent-awards-by-customer-status">Patent awards by customer status</a></li>
  <li><a href="#distribution-of-patent-awards" id="toc-distribution-of-patent-awards" class="nav-link" data-scroll-target="#distribution-of-patent-awards">Distribution of patent awards</a></li>
  <li><a href="#regional-differences-by-customer-status" id="toc-regional-differences-by-customer-status" class="nav-link" data-scroll-target="#regional-differences-by-customer-status">Regional differences by customer status</a></li>
  <li><a href="#firm-age-and-customer-status" id="toc-firm-age-and-customer-status" class="nav-link" data-scroll-target="#firm-age-and-customer-status">Firm age and customer status</a></li>
  </ul></li>
  <li><a href="#a-simple-poisson-model-via-maximum-likelihood" id="toc-a-simple-poisson-model-via-maximum-likelihood" class="nav-link" data-scroll-target="#a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</a></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a></li>
  <li><a href="#the-effect-of-blueprintys-software" id="toc-the-effect-of-blueprintys-software" class="nav-link" data-scroll-target="#the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
<p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>He Zou </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Blueprinty is a small software company that builds tools for engineering firms preparing blueprints for patent applications. Because patent applications often require detailed technical documentation, Blueprinty’s software is designed to make the application process more organized, consistent, and effective. The company’s marketing team would like to make a strong claim: firms that use Blueprinty’s software are more successful in getting patents approved.</p>
<p>At first glance, this question sounds simple. We might compare the number of patents awarded to Blueprinty customers with the number awarded to non-customers. If customers receive more patents, that could look like evidence that the software helps. However, this comparison is not enough on its own. The ideal data would track the same firms before and after they began using Blueprinty’s software, allowing us to see whether their patent success improved after adoption. Unfortunately, that kind of before-and-after data is not available.</p>
<p>Instead, Blueprinty has collected data on 1,500 mature engineering firms. For each firm, the dataset records the number of patents awarded over the past five years, the firm’s regional location, its age since incorporation, and whether or not it uses Blueprinty’s software. These data allow us to compare customers and non-customers, but they also require some caution.</p>
<p>The main challenge is that Blueprinty’s customers were not randomly selected. Firms that choose to use Blueprinty’s software may differ systematically from firms that do not. For example, customers may be older, more established, located in regions with stronger engineering ecosystems, or more experienced with the patent process. Any raw difference in patent counts could therefore reflect these firm characteristics rather than the effect of the software itself.</p>
<p>In this post, I use Poisson regression and maximum likelihood estimation to study whether Blueprinty customers tend to receive more patents, while accounting for observable differences such as firm age and region. The goal is not only to estimate the relationship between Blueprinty usage and patent awards, but also to show how maximum likelihood estimation works in a practical marketing analytics setting.</p>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<p>Before estimating a Poisson regression model, I first explore the raw patterns in the data. The outcome variable is <code>patents</code>, which records the number of patents awarded to each firm over the past five years. The main explanatory variable is <code>iscustomer</code>, which indicates whether the firm uses Blueprinty’s software. The dataset also includes each firm’s region and age, which may also be related to patent outcomes.</p>
<div id="cell-load-data" class="cell" data-message="false" data-execution_count="1">
<div id="load-data" class="cell-output cell-output-display" data-execution_count="1">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 5)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">patents</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">iscustomer</th>
<th data-quarto-table-cell-role="th">customer_status</th>
</tr>
<tr class="even">
<td>i64</td>
<td>str</td>
<td>f64</td>
<td>i64</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>"Midwest"</td>
<td>32.5</td>
<td>0</td>
<td>"Non-customers"</td>
</tr>
<tr class="even">
<td>3</td>
<td>"Southwest"</td>
<td>37.5</td>
<td>0</td>
<td>"Non-customers"</td>
</tr>
<tr class="odd">
<td>4</td>
<td>"Northwest"</td>
<td>27.0</td>
<td>1</td>
<td>"Blueprinty customers"</td>
</tr>
<tr class="even">
<td>3</td>
<td>"Northeast"</td>
<td>24.5</td>
<td>0</td>
<td>"Non-customers"</td>
</tr>
<tr class="odd">
<td>3</td>
<td>"Southwest"</td>
<td>37.0</td>
<td>0</td>
<td>"Non-customers"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The dataset contains information on engineering firms and their patent outcomes. The outcome variable, <code>patents</code>, records the number of patents awarded to each firm over the past five years. The variable <code>iscustomer</code> indicates whether the firm uses Blueprinty’s software, with 1 representing Blueprinty customers and 0 representing non-customers. The dataset also includes each firm’s <code>region</code> and <code>age</code>, which may be important because patenting activity could vary across geographic regions and across firms at different stages of maturity.</p>
<p>Before estimating a Poisson regression model, I first explore how patent outcomes differ between Blueprinty customers and non-customers. I also compare the two groups by region and firm age, because these factors could confound the relationship between software usage and patent approvals.</p>
<section id="patent-awards-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="patent-awards-by-customer-status">Patent awards by customer status</h3>
<p>A natural starting point is to compare the average number of patents awarded to Blueprinty customers and non-customers.</p>
<div id="cell-patent-means" class="cell" data-execution_count="2">
<div id="patent-means" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Customer status</th>
<th style="text-align: right;">Number of firms</th>
<th style="text-align: right;">Mean patents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blueprinty customers</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">4.13</td>
</tr>
<tr class="even">
<td>Non-customers</td>
<td style="text-align: right;">1019</td>
<td style="text-align: right;">3.47</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Blueprinty customers received an average of 4.13 patents over the past five years, compared with 3.47 patents for non-customers. This raw difference is consistent with Blueprinty’s claim that its software is associated with better patent outcomes. However, this comparison is only descriptive. Customers may differ from non-customers in other ways, so the difference should not be interpreted as causal evidence.</p>
</section>
<section id="distribution-of-patent-awards" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-patent-awards">Distribution of patent awards</h3>
<p>The average patent count is helpful, but it does not show the full distribution of patent outcomes. To better understand the data, I next compare the full distribution of patent counts for Blueprinty customers and non-customers.</p>
<div id="cell-patent-histograms" class="cell" data-fig-height="6" data-fig-width="7" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="patent-histograms" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/patent-histograms-output-1.png" width="662" height="566" class="figure-img"></p>
<figcaption>Distribution of patent awards by Blueprinty customer status.</figcaption>
</figure>
</div>
</div>
</div>
<p>Both distributions are right-skewed count distributions, with most firms receiving a relatively small number of patents. The customer distribution appears slightly shifted toward higher patent counts, but there is still substantial overlap between customers and non-customers. This supports using a count-data model, while also showing that customer status alone does not explain all variation in patent outcomes.</p>
</section>
<section id="regional-differences-by-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="regional-differences-by-customer-status">Regional differences by customer status</h3>
<p>One possible concern is that Blueprinty customers may not be geographically comparable to non-customers. If customers are concentrated in regions where firms tend to receive more patents, then the raw customer advantage could partly reflect regional differences rather than the effect of Blueprinty’s software.</p>
<div id="cell-region-distribution" class="cell" data-fig-height="3.4" data-fig-width="6.5" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="region-distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/region-distribution-output-1.png" width="614" height="316" class="figure-img"></p>
<figcaption>Regional distribution by Blueprinty customer status.</figcaption>
</figure>
</div>
</div>
</div>
<p>Blueprinty customers are much more concentrated in the Northeast than non-customers. This suggests that region is a potential confounder and should be included as a control variable in the regression model.</p>
</section>
<section id="firm-age-and-customer-status" class="level3">
<h3 class="anchored" data-anchor-id="firm-age-and-customer-status">Firm age and customer status</h3>
<p>Firm age is another potential confounder. Older firms may have more experience, larger teams, and more established patent processes.</p>
<div id="cell-age-summary" class="cell" data-execution_count="5">
<div id="age-summary" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Customer status</th>
<th style="text-align: right;">Number of firms</th>
<th style="text-align: right;">Mean age</th>
<th style="text-align: right;">Median age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Blueprinty customers</td>
<td style="text-align: right;">481</td>
<td style="text-align: right;">26.9</td>
<td style="text-align: right;">26.5</td>
</tr>
<tr class="even">
<td>Non-customers</td>
<td style="text-align: right;">1019</td>
<td style="text-align: right;">26.1</td>
<td style="text-align: right;">25.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cell-age-histograms" class="cell" data-fig-height="5.8" data-fig-width="6.5" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="age-histograms" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/age-histograms-output-1.png" width="614" height="547" class="figure-img"></p>
<figcaption>Distribution of firm age by Blueprinty customer status.</figcaption>
</figure>
</div>
</div>
</div>
<p>Blueprinty customers are slightly older on average than non-customers. Customers have a mean age of 26.9 years, compared with 26.1 years for non-customers. The difference is not large, but age may still be related to patent outcomes, so I control for both age and age squared in the regression model.</p>
<p>Overall, the exploratory analysis shows that Blueprinty customers have higher average patent counts, but they also differ from non-customers in region and age. Therefore, a simple comparison of means is not enough. The next sections use Poisson regression to estimate the relationship between Blueprinty usage and patent awards while controlling for these observable firm characteristics.</p>
</section>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<p>The outcome variable in this dataset is the number of patents awarded to each firm over the last five years. Since patents are count data, they cannot be negative and must take integer values. A normal distribution is not a natural fit for this type of outcome because it allows negative values and assumes a continuous, symmetric distribution. A Poisson distribution is a natural starting point for modeling non-negative integer outcomes.</p>
<p>For a single firm, suppose the number of patents is distributed as:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda)
\]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the expected number of patents. The probability mass function is:</p>
<p><span class="math display">\[
f(Y_i|\lambda) = \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Assuming the observations are independent and identically distributed, the joint likelihood for all firms is the product of the individual probabilities:</p>
<p><span class="math display">\[
L(\lambda|Y) = \prod_{i=1}^{n} \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking logs gives the log-likelihood:</p>
<p><span class="math display">\[
\ell(\lambda|Y)
= \sum_{i=1}^{n} \log\left(\frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}\right)
\]</span></p>
<p>Using log rules, this simplifies to:</p>
<p><span class="math display">\[
\ell(\lambda|Y)
= \sum_{i=1}^{n} \left[-\lambda + Y_i\log(\lambda) - \log(Y_i!)\right]
\]</span></p>
<p>The goal of maximum likelihood estimation is to find the value of <span class="math inline">\(\lambda\)</span> that makes the observed patent counts most likely.</p>
<div id="simple-poisson-loglikelihood" class="cell" data-message="false" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>patent_values <span class="op">=</span> blueprinty.select(<span class="st">"patents"</span>).to_series().to_numpy()</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglikelihood(lambda_value, y_values):</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> lambda_value <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="op">-</span>np.inf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    loglikelihood_values <span class="op">=</span> (</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span>lambda_value</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> y_values <span class="op">*</span> np.log(lambda_value)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> gammaln(y_values <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loglikelihood_values.<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-simple-poisson-loglikelihood-plot" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>lambda_grid <span class="op">=</span> np.linspace(<span class="fl">0.1</span>, <span class="dv">8</span>, <span class="dv">300</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>loglikelihood_grid <span class="op">=</span> np.array([</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    poisson_loglikelihood(lambda_candidate, patent_values)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lambda_candidate <span class="kw">in</span> lambda_grid</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>lambda_visual_mle <span class="op">=</span> lambda_grid[np.argmax(loglikelihood_grid)]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ax.plot(lambda_grid, loglikelihood_grid)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>ax.axvline(lambda_visual_mle, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Lambda"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Log-likelihood"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Poisson log-likelihood for patent counts"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="simple-poisson-loglikelihood-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/simple-poisson-loglikelihood-plot-output-1.png" width="696" height="376" class="figure-img"></p>
<figcaption>Log-likelihood for different values of lambda.</figcaption>
</figure>
</div>
</div>
</div>
<p>The log-likelihood reaches its maximum around <span class="math inline">\(\lambda = 3.7\)</span>. This means that, under a simple Poisson model with one common rate parameter, the most likely expected patent count is about 3.7 patents per firm. The curve also shows why maximum likelihood estimation works: we choose the parameter value that makes the observed data most likely.</p>
<p>For this simple Poisson model, the maximum likelihood estimate can also be derived analytically. The log-likelihood is:</p>
<p><span class="math display">\[
\ell(\lambda|Y)
= \sum_{i=1}^{n} \left[-\lambda + Y_i\log(\lambda) - \log(Y_i!)\right]
\]</span></p>
<p>Taking the derivative with respect to <span class="math inline">\(\lambda\)</span> gives:</p>
<p><span class="math display">\[
\frac{\partial \ell}{\partial \lambda}
= \sum_{i=1}^{n} \left[-1 + \frac{Y_i}{\lambda}\right]
= -n + \frac{\sum_{i=1}^{n}Y_i}{\lambda}
\]</span></p>
<p>Setting this equal to zero:</p>
<p><span class="math display">\[
-n + \frac{\sum_{i=1}^{n}Y_i}{\lambda} = 0
\]</span></p>
<p>Solving for <span class="math inline">\(\lambda\)</span> gives:</p>
<p><span class="math display">\[
\hat{\lambda}_{MLE}
= \frac{1}{n}\sum_{i=1}^{n}Y_i
= \bar{Y}
\]</span></p>
<p>So, in the simple Poisson model, the MLE for <span class="math inline">\(\lambda\)</span> is just the sample mean of the patent counts.</p>
<div id="cell-simple-poisson-mle" class="cell" data-message="false" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>simple_poisson_sample_mean <span class="op">=</span> patent_values.mean()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simple_poisson_negative_loglikelihood(lambda_array, y_values):</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    lambda_candidate <span class="op">=</span> <span class="bu">float</span>(lambda_array[<span class="dv">0</span>])</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_loglikelihood(lambda_candidate, y_values)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>simple_poisson_mle_result <span class="op">=</span> minimize(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    simple_poisson_negative_loglikelihood,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>np.array([simple_poisson_sample_mean]),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(patent_values,),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">"L-BFGS-B"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    bounds<span class="op">=</span>[(<span class="fl">1e-8</span>, <span class="va">None</span>)]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>simple_poisson_lambda_mle <span class="op">=</span> simple_poisson_mle_result.x[<span class="dv">0</span>]</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>simple_poisson_summary_markdown <span class="op">=</span> <span class="st">"| Quantity | Value |</span><span class="ch">\n</span><span class="st">"</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>simple_poisson_summary_markdown <span class="op">+=</span> <span class="st">"|---|---:|</span><span class="ch">\n</span><span class="st">"</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>simple_poisson_summary_markdown <span class="op">+=</span> <span class="ss">f"| Sample mean of patents | </span><span class="sc">{</span>simple_poisson_sample_mean<span class="sc">:.4f}</span><span class="ss"> |</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>simple_poisson_summary_markdown <span class="op">+=</span> <span class="ss">f"| MLE estimate of lambda | </span><span class="sc">{</span>simple_poisson_lambda_mle<span class="sc">:.4f}</span><span class="ss"> |</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>display(Markdown(simple_poisson_summary_markdown))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="simple-poisson-mle" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample mean of patents</td>
<td style="text-align: right;">3.6847</td>
</tr>
<tr class="even">
<td>MLE estimate of lambda</td>
<td style="text-align: right;">3.6847</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The numerical MLE matches the sample mean exactly up to four decimal places. Both estimates are 3.6847, which confirms the analytical result that the MLE for <span class="math inline">\(\lambda\)</span> in a simple Poisson model is the sample average of the outcome variable. In this simple model, the best estimate of the common expected patent count is about 3.68 patents per firm.</p>
<p>This model is useful for understanding maximum likelihood estimation, but it is too simple for the main research question. It assumes that every firm has the same expected number of patents, regardless of whether the firm uses Blueprinty’s software, how old the firm is, or where it is located. To study the relationship between Blueprinty usage and patent outcomes more carefully, the next step is to move from a simple Poisson model to Poisson regression.</p>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<p>The simple Poisson model estimated one common expected patent count for all firms. That is useful for understanding maximum likelihood estimation, but it is too restrictive for this case. Firms differ in age, region, and whether they use Blueprinty’s software, so it is more reasonable to allow the expected number of patents to vary across firms.</p>
<p>In a Poisson regression model, each firm has its own expected patent count:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i)
\]</span></p>
<p>Instead of treating <span class="math inline">\(\lambda_i\)</span> as constant, I model it as a function of firm characteristics:</p>
<p><span class="math display">\[
\lambda_i = \exp(X_i'\beta)
\]</span></p>
<p>The exponential function is important because <span class="math inline">\(\lambda_i\)</span> must be positive. The linear index <span class="math inline">\(X_i'\beta\)</span> can be any real number, but exponentiating it ensures that the predicted expected patent count is always greater than zero.</p>
<p>In this model, <span class="math inline">\(X_i\)</span> includes firm age, firm age squared, region indicators, and whether the firm is a Blueprinty customer. The log-likelihood for the Poisson regression model is:</p>
<p><span class="math display">\[
\ell(\beta)
= \sum_{i=1}^{n}
\left[
-\lambda_i + Y_i\log(\lambda_i) - \log(Y_i!)
\right]
\]</span></p>
<p>Since <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>, this becomes:</p>
<p><span class="math display">\[
\ell(\beta)
= \sum_{i=1}^{n}
\left[
-\exp(X_i'\beta) + Y_iX_i'\beta - \log(Y_i!)
\right]
\]</span></p>
<p>The goal is to find the coefficient vector <span class="math inline">\(\beta\)</span> that maximizes this log-likelihood.</p>
<div id="cell-poisson-regression-mle" class="cell" data-message="false" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta_values, x_values, y_values):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    linear_prediction_values <span class="op">=</span> x_values <span class="op">@</span> beta_values</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    lambda_values <span class="op">=</span> np.exp(linear_prediction_values)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    loglikelihood_values <span class="op">=</span> (</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span>lambda_values</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        <span class="op">+</span> y_values <span class="op">*</span> linear_prediction_values</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="op">-</span> gammaln(y_values <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loglikelihood_values.<span class="bu">sum</span>()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_negative_loglikelihood(beta_values, x_values, y_values):</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_regression_loglikelihood(beta_values, x_values, y_values)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_gradient_negative_loglikelihood(beta_values, x_values, y_values):</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    linear_prediction_values <span class="op">=</span> x_values <span class="op">@</span> beta_values</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    lambda_values <span class="op">=</span> np.exp(linear_prediction_values)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    gradient_values <span class="op">=</span> x_values.T <span class="op">@</span> (lambda_values <span class="op">-</span> y_values)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> gradient_values</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_hessian_negative_loglikelihood(beta_values, x_values, y_values):</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    linear_prediction_values <span class="op">=</span> x_values <span class="op">@</span> beta_values</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    lambda_values <span class="op">=</span> np.exp(linear_prediction_values)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    hessian_values <span class="op">=</span> x_values.T <span class="op">@</span> (lambda_values[:, <span class="va">None</span>] <span class="op">*</span> x_values)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> hessian_values</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>poisson_regression_initial_beta <span class="op">=</span> np.zeros(poisson_regression_x.shape[<span class="dv">1</span>])</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>poisson_regression_initial_beta[<span class="dv">0</span>] <span class="op">=</span> np.log(poisson_regression_y.mean())</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>poisson_regression_mle_result <span class="op">=</span> minimize(</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    poisson_regression_negative_loglikelihood,</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>    x0<span class="op">=</span>poisson_regression_initial_beta,</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>(poisson_regression_x, poisson_regression_y),</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    method<span class="op">=</span><span class="st">"trust-exact"</span>,</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>    jac<span class="op">=</span>poisson_regression_gradient_negative_loglikelihood,</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>    hess<span class="op">=</span>poisson_regression_hessian_negative_loglikelihood</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>poisson_regression_beta_mle <span class="op">=</span> poisson_regression_mle_result.x</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>poisson_regression_hessian_mle <span class="op">=</span> poisson_regression_hessian_negative_loglikelihood(</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>    poisson_regression_beta_mle,</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>    poisson_regression_x,</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>    poisson_regression_y</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>poisson_regression_covariance_matrix <span class="op">=</span> np.linalg.inv(poisson_regression_hessian_mle)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>poisson_regression_standard_errors <span class="op">=</span> np.sqrt(np.diag(poisson_regression_covariance_matrix))</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>poisson_regression_z_values <span class="op">=</span> poisson_regression_beta_mle <span class="op">/</span> poisson_regression_standard_errors</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>poisson_regression_mle_result.success, poisson_regression_mle_result.message</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="poisson-regression-mle" class="cell-output cell-output-display" data-execution_count="11">
<pre><code>(False, 'A bad approximation caused failure to predict improvement.')</code></pre>
</div>
</div>
<div id="cell-poisson-regression-mle-table" class="cell" data-execution_count="12">
<div id="poisson-regression-mle-table" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: right;">-0.5089</td>
<td style="text-align: right;">0.1832</td>
<td style="text-align: right;">-2.78</td>
</tr>
<tr class="even">
<td>Age</td>
<td style="text-align: right;">0.1486</td>
<td style="text-align: right;">0.0139</td>
<td style="text-align: right;">10.72</td>
</tr>
<tr class="odd">
<td>Age squared</td>
<td style="text-align: right;">-0.0030</td>
<td style="text-align: right;">0.0003</td>
<td style="text-align: right;">-11.51</td>
</tr>
<tr class="even">
<td>Northeast</td>
<td style="text-align: right;">0.0292</td>
<td style="text-align: right;">0.0436</td>
<td style="text-align: right;">0.67</td>
</tr>
<tr class="odd">
<td>Northwest</td>
<td style="text-align: right;">-0.0176</td>
<td style="text-align: right;">0.0538</td>
<td style="text-align: right;">-0.33</td>
</tr>
<tr class="even">
<td>South</td>
<td style="text-align: right;">0.0566</td>
<td style="text-align: right;">0.0527</td>
<td style="text-align: right;">1.07</td>
</tr>
<tr class="odd">
<td>Southwest</td>
<td style="text-align: right;">0.0506</td>
<td style="text-align: right;">0.0472</td>
<td style="text-align: right;">1.07</td>
</tr>
<tr class="even">
<td>Blueprinty customer</td>
<td style="text-align: right;">0.2076</td>
<td style="text-align: right;">0.0309</td>
<td style="text-align: right;">6.72</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table reports the Poisson regression estimates obtained by maximizing the log-likelihood directly. The model controls for firm age, age squared, region, and Blueprinty customer status.</p>
<p>The main coefficient of interest is <code>Blueprinty customer</code>. Its estimate is 0.2076, with a z value of 6.72. This suggests that Blueprinty customers have higher expected patent counts than similar non-customers, after controlling for age and region.</p>
<p>Because Poisson regression uses a log link, this coefficient is not interpreted as 0.2076 additional patents. Instead, exponentiating the coefficient gives:</p>
<p><span class="math display">\[
\exp(0.2076) \approx 1.23
\]</span></p>
<p>This means that Blueprinty customers are predicted to have about 23% higher expected patent counts than comparable non-customers, holding the other variables fixed.</p>
<p>The age coefficient is positive and the age-squared coefficient is negative, suggesting that patenting increases with firm age but at a decreasing rate. The region variables are included as controls, with the Midwest as the reference region.</p>
<p>To check the manual maximum likelihood estimates, I fit the same Poisson regression model using <code>statsmodels</code>. The estimates should match the coefficients obtained from the custom likelihood function.</p>
<div id="cell-poisson-regression-glm-check" class="cell" data-message="false" data-execution_count="13">
<div id="poisson-regression-glm-check" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Manual MLE</th>
<th style="text-align: right;">statsmodels GLM</th>
<th style="text-align: right;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td style="text-align: right;">-0.5089</td>
<td style="text-align: right;">-0.5089</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td>Age</td>
<td style="text-align: right;">0.1486</td>
<td style="text-align: right;">0.1486</td>
<td style="text-align: right;">-0.000000</td>
</tr>
<tr class="odd">
<td>Age squared</td>
<td style="text-align: right;">-0.0030</td>
<td style="text-align: right;">-0.0030</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td>Northeast</td>
<td style="text-align: right;">0.0292</td>
<td style="text-align: right;">0.0292</td>
<td style="text-align: right;">-0.000000</td>
</tr>
<tr class="odd">
<td>Northwest</td>
<td style="text-align: right;">-0.0176</td>
<td style="text-align: right;">-0.0176</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td>South</td>
<td style="text-align: right;">0.0566</td>
<td style="text-align: right;">0.0566</td>
<td style="text-align: right;">-0.000000</td>
</tr>
<tr class="odd">
<td>Southwest</td>
<td style="text-align: right;">0.0506</td>
<td style="text-align: right;">0.0506</td>
<td style="text-align: right;">-0.000000</td>
</tr>
<tr class="even">
<td>Blueprinty customer</td>
<td style="text-align: right;">0.2076</td>
<td style="text-align: right;">0.2076</td>
<td style="text-align: right;">-0.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The manual MLE estimates match the <code>statsmodels</code> GLM estimates exactly up to the displayed decimal places. The differences are essentially zero for every coefficient. This confirms that the custom log-likelihood function and numerical optimization procedure are correctly estimating the Poisson regression model.</p>
<p>This check is important because it connects the maximum likelihood recipe to the standard regression tool. The built-in GLM function is not doing something fundamentally different; it is also estimating the Poisson regression coefficients by maximum likelihood.</p>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<p>The coefficient on <code>Blueprinty customer</code> is positive, but it is not directly interpretable as the number of additional patents. Poisson regression is multiplicative because the model predicts expected patents as:</p>
<p><span class="math display">\[
\lambda_i = \exp(X_i'\beta)
\]</span></p>
<p>To make the result easier to interpret, I use the fitted model to create two counterfactual predictions. First, I predict each firm’s expected patent count as if every firm were a non-customer. Then, I predict each firm’s expected patent count as if every firm were a Blueprinty customer. The difference between these two predictions gives an estimate of the effect of customer status while holding each firm’s age and region fixed.</p>
<div id="cell-blueprinty-counterfactual-effect" class="cell" data-execution_count="14">
<div id="blueprinty-counterfactual-effect" class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Average predicted patents if all firms are non-customers</td>
<td style="text-align: right;">3.436</td>
</tr>
<tr class="even">
<td>Average predicted patents if all firms are Blueprinty customers</td>
<td style="text-align: right;">4.229</td>
</tr>
<tr class="odd">
<td>Average effect of Blueprinty customer status</td>
<td style="text-align: right;">0.793</td>
</tr>
<tr class="even">
<td>Percent effect from customer coefficient</td>
<td style="text-align: right;">23.1%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The counterfactual predictions make the Blueprinty effect easier to interpret. If every firm were treated as a non-customer, the model predicts an average of 3.436 patents per firm. If every firm were treated as a Blueprinty customer, while keeping the same age and region values, the predicted average increases to 4.229 patents per firm.</p>
<p>The estimated average difference is 0.793 patents per firm over five years. In percentage terms, the customer coefficient implies that Blueprinty customers have about 23.1% higher expected patent counts than comparable non-customers.</p>
<p>This result supports Blueprinty’s marketing claim that its software is associated with more patent approvals. However, the conclusion should still be stated carefully. The data are observational, not experimental, so the model controls for observed differences such as age and region, but it cannot rule out all possible unobserved differences between customers and non-customers.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This analysis used maximum likelihood estimation to fit a Poisson regression model for patent counts. Starting with a simple Poisson model showed that the MLE for a single common rate parameter is the sample mean. Extending the model to Poisson regression allowed expected patent counts to vary with firm age, region, and Blueprinty customer status.</p>
<p>The main result is that Blueprinty customer status is positively associated with patent awards. After controlling for age and region, the model predicts that Blueprinty customers receive about 0.793 more patents per firm over five years, or about 23.1% higher expected patent counts than comparable non-customers.</p>
<p>Overall, the evidence is favorable for Blueprinty’s marketing claim, but it should not be interpreted as definitive causal proof. Since firms were not randomly assigned to use Blueprinty’s software, unobserved differences between customers and non-customers may still affect the results.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>